### ISSUE TITLE
getaddrinfo fails to retrive HTTP query due to missing of protocol info

### ISSUE THREAD

**Issue by rilysh** [jhx0/net-utils#1]
Hi!
I noticed that `getaddrinfo` can't able to resolve the domain (`icanhazip.com`) in (`getip.c`), and all other passed domains in these programs, (`dns.c`) and (`header.c`) due to missing of provided protocol family, socket type, and the protocol itself on `addrinfo` in `util.h`. 

I'm using Void Linux (lh-6.1.9_1)
#### Image
![image](https://user-images.githubusercontent.com/71683721/216783853-b5cad135-61c0-403a-aeaa-c1637dce47c3.png)

The easy solution would be implicitly mentioning this missing members in `addrinfo`

After applying this, there's also an issue I noticed with `dns.c` is that `inet_ntop` try to access socket address data with an indexing array, where the index is 2, however, there is no guarantee that `sa_data[2]` will be available. For that I also patched it.

Also, an issue with `header.c` is that if the response of the HTTP server isn't 302 then it can't able to retrieve the header.  For example, `./header freebsd.org` where FreeBSD server seems returns a different location `https://96.47.72.84`. But if we do the same, for example `./header netbsd.org`, we'll get a connection refused error.

I'm not exactly sure if there's any difference between different Linux kernel network configurations, but it seems very unlikely...

Patch file: [here](https://postit.ilinux.fr/?670b70e7af0145dc#3iEn2u7939sM5UGvh8Bj2qVyW9xMkq3rezkv1bMD9QMv)

**Comment by jhx0** [comment]
Hey @rilysh! :)

Indeed, there were quite some issues in the code. I honestly ask myself how i did not see that before.
I have applied the patch and only changed the memset() calls to the provided CLEAR() macro.
The patch was committed a couple of minutes ago - since these fixes are very urgent!

Thanks for taking your time to address all the issues! ;)

**Comment by rilysh** [comment]
Great, since everything is fixed now, I'll close this issue.
Have a ~~great~~ wonderful Sunday!

**Comment by jhx0** [comment]
Alright, seems good so far.
Have a good sunday to @rilysh ;)
